// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ToolWindowVSIXPR
{
    internal sealed partial class Vsix
    {
        public const string Id = "ToolWindowVSIXPR.962a86b4-ce2f-4817-8018-941276c2eebf";
        public const string Name = "ToolWindowVSIXPR";
        public const string Description = @"Power Tools Test";
        public const string Language = "fr-FR";
        public const string Version = "1.0.1";
        public const string Author = "Company";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
